config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:show, :new, :create, :edit] do
    resource :upvote, only: [:create]
    resource :downvote, only: [:create]
  end



  get "/api/v1/links", to: "links#index" , as: "json_index"

  post "/api/v1/links", to: "links#create" , as: "json_create"
  get "/new", to: "new_links#index", as: "new_links"
  get "/change_vote", to: "links#change_vote", as: "change_vote"
  root to: "links#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
validates :title, presence: :true
validates :url, presence: :true
has_many :scores

	

	def upvote
		self.upvotes +=1
		self.save
	end

	def downvote
		self.downvotes +=1
		self.save
	end

	def score
		Score.new(self)
	end

	def self.newest_first
		order("created_at DESC").all
	end

	def self.hottest_first
		Link.all.sort_by(&:sort)
	end

	def sort
		self.downvotes - self.upvotes 
	end

	def image?
		self.url.end_with?(".jpg", ".gif", ".png")
	end

end

app/models/score.rb
class Score
  CONTROVERSIAL_THRESHOLD = 0.2 #to be filled

  def initialize(link)
    # byebug
    @upvotes = link.upvotes
    @downvotes = link.downvotes
    #to be completed
  end

  def upvotes
    @upvotes
  end

  def downvotes
    @downvotes
  end

  def value
    @upvotes - @downvotes
  end

  def controversial?
    #this code may not be correct
    score_delta_percentage < 0.2
  end

  def ==(other)
    other.upvotes == upvotes && other.downvotes == downvotes
  end

  alias :eql? :==

  def hash
    [upvotes, downvotes].hash
  end

  private

  def score_delta_percentage
    score_delta.to_f / high_score
  end

  def high_score
    [upvotes, downvotes].max
  end

  def score_delta
    value.abs
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::BaseController
  def index
    links = Link.hottest_first
    render json: links
  end

  def create
    #to be implemented
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/link_mailer.rb
class LinkMailer 

	def self.new_link(link)
		
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  def index	

    respond_to do |format|
      
      format.json do
        byebug
      end

      format.html do
        @link = Link.all
      end

    end

  end
  
  def new
  	
  end

  def create
    # byebug
  	@link = Link.new(link_params)
  		if @link.save
  			flash[:message] = "Successful"
        LinkMailer.new_link(@link)
  			redirect_to root_path
  		else
  			render :new
  		end
  end

  def show
    # byebug
    @link = Link.find(params[:id])
    # render :show
  end

  def change_vote
    # @params_file = params
    @link = Link.find(params[:link][:id])

    if params[:commit] == "Downvote"
      @link.downvote
      # @link.save
      # byebug
    elsif params[:commit] == "Upvote"
      @link.upvote
      # @link.save
      # byebug
    end
    # render :index
    redirect_to @link
  end

	private

	def link_params
		params.require(:link).permit(:title, :url, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_score_for(score)
  	diff = score.upvotes - score.downvotes
  	# byebug
  	formatted_score = diff.to_s + " (+" + score.upvotes.to_s + "," + " -" + score.downvotes.to_s + ")"

    #to be implemented
  end
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <div>
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% target.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkSharer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "navigation" %>

  <%= yield %>

</body>
</html>

app/views/links/_link.html.erb
partial form

<img src=<%=link.url%>>

app/views/links/index.html.erb
<div class="container">

	<h1>List Page</h1>

	<ul id="links">
		<% Link.hottest_first.each do |l| %>

				<li id="links">
					<%=link_to l.title, l.url%>
					<% if l.url.end_with?(".jpg", ".gif", ".png")%>
						<%= render "link", link: l %>
					<% end %>

					<%= form_for l, :html => { :id => "link_#{l.id}" }, :url => change_vote_path, method: :get do |f|%>
						<%= f.hidden_field :id , :value => l.id %>
						<%= f.submit "Downvote", "data-role" => "score"%>
						<%= f.submit "Upvote", "data-role" => "score"%>
					<% end %>

				</li>

		<% end %>
	</ul>

	<%= link_to "Submit a new link", new_link_path %>
	
	<%= link_to "new", new_link_path%>
</div>

app/views/links/new.html.erb
<div class="container">

	<ul id="links">
		<% Link.newest_first.each do |l| %>
			<li>
				<%= l.title%>
				<%=link_to l.title, l.url%>		
			</li>

		<% end %>
	</ul>
	
	<h1>Create a new link</h1>

	<%= form_for Link.new do |f| %>

	<div>
		<h6> Link Title: </h6>
		<%= f.text_field :title, :placeholder => "Be clear and descriptive" %>
	</div>
	
	<div>
		<h6> Url: </h6>
	<%= f.text_field :url, :placeholder => "the damn url,please" %>
	</div>

	<div>
		<h6>Upload your image</h6>
   	<%= f.file_field :image, multiple: true %>
	</div>
	<div>
		<%= f.submit "Submit!" %>
	</div>
	<% end %>
</div>

app/views/links/show.html.erb
<br>

<%=link_to @link.title, link_path%>
<% if @link.url.end_with?(".jpg", ".gif", ".png")%>
	<%= render "link", link: @link %>
<% end %>



<ul id=<%= "link_#{@link.id}" %>>
	<li data-role="score" >Votes : <%=@link.upvotes - @link.downvotes%>
	</li>
</ul>